DROP DATABASE IF EXISTS TCRESERVATION;
CREATE DATABASE TCRESERVATION;
USE TCRESERVATION;

-- Users are anyone who are having currently reservations
DROP TABLE IF EXISTS USER;
CREATE TABLE USER (
uID INT,
fName VARCHAR(15) NOT NULL,
lName VARCHAR(15) NOT NULL,
phone VARCHAR(12) DEFAULT '000-000-0000',
balance INT DEFAULT 0,
PRIMARY KEY (uID)
);

DROP TABLE IF EXISTS COURT;
CREATE TABLE COURT (
cID INT,
PRIMARY KEY (cID)
);

DROP TABLE IF EXISTS TIME;
CREATE TABLE TIME (
tID INT,
rDate DATE,
startTime DATETIME,
duration FLOAT DEFAULT 0,
PRIMARY KEY (tID)
);

-- Each tuple contains one reservation detail
DROP TABLE IF EXISTS RESERVATION;
CREATE TABLE RESERVATION (
uID INT,
cID INT,
tID INT,
rentEqmt ENUM('yes', 'no') DEFAULT 'no',
FOREIGN KEY (uID) REFERENCES USER(uID) ON DELETE CASCADE,
FOREIGN KEY (cID) REFERENCES COURT(cID) ON DELETE CASCADE,
FOREIGN KEY (tID) REFERENCES TIME(tID) ON UPDATE CASCADE
);

DROP TABLE IF EXISTS MEMBER;
CREATE TABLE MEMBER (
mID INT, -- If is a member, uID will be the same as mID
expirationDate DATE,
phone VARCHAR(12),
birthday DATE,
PRIMARY KEY (mID)
);

DROP TABLE IF EXISTS EQUIPMENT;
CREATE TABLE EQUIPMENT (
uID INT,
numRacket INT,
numBall INT,
tID INT,
FOREIGN KEY (uID) REFERENCES USER(uID) ON DELETE CASCADE,
FOREIGN KEY (tID) REFERENCES TIME(tID) ON DELETE CASCADE
);
  
LOAD DATA LOCAL INFILE 'users.txt' INTO TABLE USER;
LOAD DATA LOCAL INFILE 'courts.txt' INTO TABLE COURT;
LOAD DATA LOCAL INFILE 'times.txt' INTO TABLE TIME;
-- LOAD DATA LOCAL INFILE 'reservations.txt' INTO TABLE RESERVATION;
-- LOAD DATA LOCAL INFILE 'members.txt' INTO TABLE MEMBER;
-- LOAD DATA LOCAL INFILE 'equipments.txt' INTO TABLE EQUIPMENT;
source reservations.sql;
